# Generated by Django 5.2 on 2025-04-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='atendimento',
            new_name='ambiente_climatizado',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='atendimento_agil',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mix_produtos',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='prazo_entrega',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='valores_produtos',
        ),
        migrations.AddField(
            model_name='feedback',
            name='atendimento_manicures',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='atendimento_recepcao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='dificuldade_totem',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='limpeza_organizacao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='oferta_ajuda',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
